version: '3.8'

services:
  # ========= Tapo Cams =========
  ucp_giardino_cucina:
    build: .
    container_name: ucp_giardino_cucina
    restart: always
    volumes: [ "./client.pem:/client.pem:ro" ]
    command: >-
      unifi-cam-proxy -H ${PROTECT_HOST} --mac '02:42:ac:11:00:10'
      -i 192.168.31.10 -c /client.pem -t ${PROTECT_TOKEN}
      tapo -u username -p password --single-stream stream2
      --ffmpeg-args='-rtsp_transport tcp -timeout 15000000 -c:v libx264 -preset ultrafast -tune zerolatency -pix_fmt yuv420p -profile:v baseline -level 4.0 -x264-params keyint=30:min-keyint=30:scenecut=0:nal-hrd=cbr -g 30 -sc_threshold 0 -b:v 3000k -maxrate 3000k -bufsize 6000k -bsf:v filter_units=remove_types=6 -c:a aac -ar 32000 -ac 1 -b:a 32k'

  ucp_cucina:
    build: .
    container_name: ucp_cucina
    restart: always
    volumes: [ "./client.pem:/client.pem:ro" ]
    command: >-
      unifi-cam-proxy -H ${PROTECT_HOST} --mac '02:42:ac:11:00:18'
      -i 192.168.31.18 -c /client.pem -t ${PROTECT_TOKEN}
      tapo -u username -p password --single-stream stream2
      --ffmpeg-args='-rtsp_transport tcp -timeout 15000000 -c:v libx264 -preset ultrafast -tune zerolatency -pix_fmt yuv420p -profile:v baseline -level 4.0 -x264-params keyint=30:min-keyint=30:scenecut=0:nal-hrd=cbr -g 30 -sc_threshold 0 -b:v 3000k -maxrate 3000k -bufsize 6000k -bsf:v filter_units=remove_types=6 -c:a aac -ar 32000 -ac 1 -b:a 32k'

  ucp_strada:
    build: .
    container_name: ucp_strada
    restart: always
    volumes: [ "./client.pem:/client.pem:ro" ]
    command: >-
      unifi-cam-proxy -H ${PROTECT_HOST} --mac '02:42:ac:11:00:13'
      -i 192.168.31.13 -c /client.pem -t ${PROTECT_TOKEN}
      tapo -u username -p password --single-stream stream2
      --ffmpeg-args='-rtsp_transport tcp -timeout 15000000 -c:v libx264 -preset ultrafast -tune zerolatency -pix_fmt yuv420p -profile:v baseline -level 4.0 -x264-params keyint=30:min-keyint=30:scenecut=0:nal-hrd=cbr -g 30 -sc_threshold 0 -b:v 3000k -maxrate 3000k -bufsize 6000k -bsf:v filter_units=remove_types=6 -c:a aac -ar 32000 -ac 1 -b:a 32k'

  ucp_portone:
    build: .
    container_name: ucp_portone
    restart: always
    volumes: [ "./client.pem:/client.pem:ro" ]
    command: >-
      unifi-cam-proxy -H ${PROTECT_HOST} --mac '02:42:ac:11:00:14'
      -i 192.168.31.14 -c /client.pem -t ${PROTECT_TOKEN}
      tapo -u username -p password --single-stream stream2
      --ffmpeg-args='-rtsp_transport tcp -timeout 15000000 -c:v libx264 -preset ultrafast -tune zerolatency -pix_fmt yuv420p -profile:v baseline -level 4.0 -x264-params keyint=30:min-keyint=30:scenecut=0:nal-hrd=cbr -g 30 -sc_threshold 0 -b:v 3000k -maxrate 3000k -bufsize 6000k -bsf:v filter_units=remove_types=6 -c:a aac -ar 32000 -ac 1 -b:a 32k'

  ucp_studio:
    build: .
    container_name: ucp_studio
    restart: always
    volumes: [ "./client.pem:/client.pem:ro" ]
    command: >-
      unifi-cam-proxy -H ${PROTECT_HOST} --mac '02:42:ac:11:00:05'
      -i 192.168.31.5 -c /client.pem -t ${PROTECT_TOKEN}
      tapo -u username -p password --single-stream stream2
      --ffmpeg-args='-rtsp_transport tcp -timeout 15000000 -c:v libx264 -preset ultrafast -tune zerolatency -pix_fmt yuv420p -profile:v baseline -level 4.0 -x264-params keyint=30:min-keyint=30:scenecut=0:nal-hrd=cbr -g 30 -sc_threshold 0 -b:v 3000k -maxrate 3000k -bufsize 6000k -bsf:v filter_units=remove_types=6 -c:a aac -ar 32000 -ac 1 -b:a 32k'

  ucp_ingresso:
    build: .
    container_name: ucp_ingresso
    restart: always
    volumes: [ "./client.pem:/client.pem:ro" ]
    command: >-
      unifi-cam-proxy -H ${PROTECT_HOST} --mac '02:42:ac:11:00:17'
      -i 192.168.31.17 -c /client.pem -t ${PROTECT_TOKEN}
      tapo -u username -p password --single-stream stream2
      --ffmpeg-args='-rtsp_transport tcp -timeout 15000000 -c:v libx264 -preset ultrafast -tune zerolatency -pix_fmt yuv420p -profile:v baseline -level 4.0 -x264-params keyint=30:min-keyint=30:scenecut=0:nal-hrd=cbr -g 30 -sc_threshold 0 -b:v 3000k -maxrate 3000k -bufsize 6000k -bsf:v filter_units=remove_types=6 -c:a aac -ar 32000 -ac 1 -b:a 32k'

  ucp_zonanotte:
    build: .
    container_name: ucp_zonanotte
    restart: always
    volumes: [ "./client.pem:/client.pem:ro" ]
    command: >-
      unifi-cam-proxy -H ${PROTECT_HOST} --mac '02:42:ac:11:00:16'
      -i 192.168.31.16 -c /client.pem -t ${PROTECT_TOKEN}
      tapo -u username -p password --single-stream stream2
      --ffmpeg-args='-rtsp_transport tcp -timeout 15000000 -c:v libx264 -preset ultrafast -tune zerolatency -pix_fmt yuv420p -profile:v baseline -level 4.0 -x264-params keyint=30:min-keyint=30:scenecut=0:nal-hrd=cbr -g 30 -sc_threshold 0 -b:v 3000k -maxrate 3000k -bufsize 6000k -bsf:v filter_units=remove_types=6 -c:a aac -ar 32000 -ac 1 -b:a 32k'

  ucp_salotto:
    build: .
    container_name: ucp_salotto
    restart: always
    volumes: [ "./client.pem:/client.pem:ro" ]
    command: >-
      unifi-cam-proxy -H ${PROTECT_HOST} --mac '02:42:ac:11:00:19'
      -i 192.168.31.19 -c /client.pem -t ${PROTECT_TOKEN}
      tapo -u username -p password --single-stream stream2
      --ffmpeg-args='-rtsp_transport tcp -timeout 15000000 -c:v libx264 -preset ultrafast -tune zerolatency -pix_fmt yuv420p -profile:v baseline -level 4.0 -x264-params keyint=30:min-keyint=30:scenecut=0:nal-hrd=cbr -g 30 -sc_threshold 0 -b:v 3000k -maxrate 3000k -bufsize 6000k -bsf:v filter_units=remove_types=6 -c:a aac -ar 32000 -ac 1 -b:a 32k'

  # ========= Non-Tapo (Hikvision/altre) =========
  # ucp_giardino_matrimoniale:
  #   build: .
  #   container_name: ucp_giardino_matrimoniale
  #   restart: always
  #   volumes: [ "./client.pem:/client.pem:ro" ]
  #   command: >-
  #     unifi-cam-proxy -H ${PROTECT_HOST} --mac '02:42:ac:11:00:11'
  #     -c /client.pem -t ${PROTECT_TOKEN}
  #     hikvision -i 192.168.31.11 -u aaa -p aaa
  #     --ffmpeg-args='-rtsp_transport tcp -timeout 15000000 -c:v libx264 -preset ultrafast -tune zerolatency -pix_fmt yuv420p -profile:v baseline -level 4.0 -x264-params keyint=30:min-keyint=30:scenecut=0:nal-hrd=cbr -g 30 -sc_threshold 0 -b:v 3000k -maxrate 3000k -bufsize 6000k -bsf:v filter_units=remove_types=6 -c:a aac -ar 32000 -ac 1 -b:a 32k'

  # ucp_garage:
  #   build: .
  #   container_name: ucp_garage
  #   restart: always
  #   volumes: [ "./client.pem:/client.pem:ro" ]
  #   command: >-
  #     unifi-cam-proxy -H ${PROTECT_HOST} --mac '02:42:ac:11:00:12'
  #     -c /client.pem -t ${PROTECT_TOKEN}
  #     hikvision -i 192.168.31.12 -u aaa -p aaa
  #     --ffmpeg-args='-rtsp_transport tcp -timeout 15000000 -c:v libx264 -preset ultrafast -tune zerolatency -pix_fmt yuv420p -profile:v baseline -level 4.0 -x264-params keyint=30:min-keyint=30:scenecut=0:nal-hrd=cbr -g 30 -sc_threshold 0 -b:v 3000k -maxrate 3000k -bufsize 6000k -bsf:v filter_units=remove_types=6 -c:a aac -ar 32000 -ac 1 -b:a 32k'
 