version: '3.8'

services:
  # ========= Tapo Cams =========
  camera1:
    build: .
    container_name: camera1
    restart: always
    volumes: [ "./client.pem:/client.pem:ro" ]
    command: >-
      unifi-cam-proxy -H ${PROTECT_HOST} --mac '02:42:ac:11:00:10'
      -i 192.168.31.10 -c /client.pem -t ${PROTECT_TOKEN}
      tapo -u username -p password
      --ffmpeg-args='-rtsp_transport tcp -timeout 15000000 -c:v libx264 -preset ultrafast -tune zerolatency -pix_fmt yuv420p -profile:v baseline -level 4.0 -x264-params keyint=30:min-keyint=30:scenecut=0:nal-hrd=cbr -g 30 -sc_threshold 0 -b:v 3000k -maxrate 3000k -bufsize 6000k -bsf:v filter_units=remove_types=6 -c:a aac -ar 32000 -ac 1 -b:a 32k'